package com.geebeeayy.app.data

import android.content.Context
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder

/**
 * Box art fetched from libretro's thumbnail server, for carts the player has
 * no picture for.
 *
 * **Never bundled.** The art belongs to each game's publisher; libretro's own
 * README says so. Fetching it to a player's device at their request makes this
 * app a client, the same posture as a browser. Shipping the pictures inside
 * the APK would make it a distributor. The line matters more than the feature
 * does - see `docs/cover-art.md`.
 *
 * Off unless the player turns it on, because an offline-first emulator should
 * not reach the network on its own.
 */
object CoverArt {

    /** Where a downloaded cover lands. [RomArtwork] looks here last. */
    fun cacheDir(context: Context): File =
        File(context.filesDir, "covers").apply { mkdirs() }

    fun cachedFile(context: Context, romPath: String): File =
        File(cacheDir(context), "${File(romPath).nameWithoutExtension}.png")

    /**
     * A tried-and-failed marker, so a cart with no art on the server is not
     * re-requested on every scroll. Deleted by [clearCache], which is how a
     * player retries.
     */
    private fun missFile(context: Context, romPath: String): File =
        File(cacheDir(context), "${File(romPath).nameWithoutExtension}.miss")

    /**
     * Fetch the cover for [romPath] if it is not already cached.
     *
     * Returns the file on success, null when there is nothing to show. Blocking:
     * call it off the main thread.
     */
    fun fetch(context: Context, romPath: String): File? {
        val cached = cachedFile(context, romPath)
        if (cached.isFile) return cached
        if (missFile(context, romPath).isFile) return null

        for (name in candidateNames(context, romPath)) {
            val file = download(name, cached)
            if (file != null) return file
        }
        runCatching { missFile(context, romPath).createNewFile() }
        return null
    }

    /**
     * The No-Intro names worth trying, best first.
     *
     * **Two mechanisms, because neither covers the set on its own.** The game
     * code is inside the cart, so it survives a rename and a trim - but 474 of
     * the DAT's 3692 entries carry no code at all, and 289 of those are
     * ordinary retail games. *Yggdra Union* is one: the cart reads `BYUE` and
     * the DAT does not list it. The filename path catches exactly those, when
     * the file still carries its No-Intro name.
     */
    internal fun candidateNames(context: Context, romPath: String): List<String> {
        val names = mutableListOf<String>()
        gameCode(File(romPath))?.let { code -> codeIndex(context)[code]?.let(names::add) }
        val fileName = File(romPath).nameWithoutExtension
        if (fileName !in names) names += fileName
        return names
    }

    private fun gameCode(rom: File): String? =
        RomHeader.read(rom)?.gameCode?.takeIf { it.length == 4 }

    @Volatile
    private var index: Map<String, String>? = null

    /**
     * Game code to No-Intro name, read once from the APK's assets.
     *
     * Generated by `tools/gen-cover-index.py` from libretro-database, which is
     * CC-BY-SA-4.0 - credited in Settings.
     */
    private fun codeIndex(context: Context): Map<String, String> {
        index?.let { return it }
        val loaded = runCatching {
            context.assets.open(ASSET).bufferedReader().use { reader ->
                parseIndex(reader.readText())
            }
        }.getOrDefault(emptyMap())
        index = loaded
        return loaded
    }

    /**
     * A flat `{"BTME":"Mario Tennis - ..."}` object, parsed by hand.
     *
     * `org.json` is on the platform and would do this in a line, but it is not
     * on the JVM the unit tests run on, and this file is the one place where
     * getting a name wrong means fetching somebody else's box art.
     */
    internal fun parseIndex(json: String): Map<String, String> {
        val out = LinkedHashMap<String, String>()
        var i = 0
        fun readString(): String? {
            while (i < json.length && json[i] != '"') {
                if (json[i] == '}') return null
                i++
            }
            if (i >= json.length) return null
            i++
            val sb = StringBuilder()
            while (i < json.length && json[i] != '"') {
                if (json[i] == '\\' && i + 1 < json.length) {
                    i++
                    sb.append(
                        when (json[i]) {
                            'n' -> '\n'
                            't' -> '\t'
                            'u' -> {
                                val code = json.substring(i + 1, i + 5).toInt(16).toChar()
                                i += 4
                                code
                            }
                            else -> json[i]
                        }
                    )
                } else {
                    sb.append(json[i])
                }
                i++
            }
            i++
            return sb.toString()
        }
        while (true) {
            val key = readString() ?: break
            val value = readString() ?: break
            out[key] = value
        }
        return out
    }

    /** The thumbnail URL for a No-Intro [name]. */
    internal fun urlFor(name: String): String =
        "$BASE/${encode(name)}.png"

    /**
     * `URLEncoder` is form encoding, which turns a space into `+` and leaves
     * `*` alone. The server wants path encoding, so those two are corrected.
     */
    private fun encode(segment: String): String =
        URLEncoder.encode(segment, "UTF-8")
            .replace("+", "%20")
            .replace("*", "%2A")

    private fun download(name: String, into: File): File? = runCatching {
        val connection = (URL(urlFor(name)).openConnection() as HttpURLConnection).apply {
            connectTimeout = 10_000
            readTimeout = 20_000
            instanceFollowRedirects = true
        }
        try {
            if (connection.responseCode != HttpURLConnection.HTTP_OK) return@runCatching null
            // Written beside the target and renamed, so a dropped connection
            // cannot leave a half-decoded PNG that looks cached.
            val temp = File(into.parentFile, "${into.name}.part")
            connection.inputStream.use { input ->
                temp.outputStream().use { output -> input.copyTo(output) }
            }
            if (temp.renameTo(into)) into else null.also { temp.delete() }
        } finally {
            connection.disconnect()
        }
    }.getOrNull()

    /** Forgets every download, including the tried-and-failed markers. */
    fun clearCache(context: Context) {
        cacheDir(context).listFiles()?.forEach { it.delete() }
    }

    fun cacheBytes(context: Context): Long =
        cacheDir(context).listFiles()?.sumOf { it.length() } ?: 0L

    private const val ASSET = "gba-game-codes.json"
    private const val BASE =
        "https://thumbnails.libretro.com/Nintendo%20-%20Game%20Boy%20Advance/Named_Boxarts"
}
